### ISSUE TITLE
YANK with SAMS performance info

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1008]
Hi there, 
I was trying the latest conda version of YANK 0.22.1 running ABFE on toluene bonded to lysozyme. To perform 1000 YANK iterations (complex state) by using a GTX 1080 the required simulation time ~ 2days and 9hrs. The same system simulated by using YANK 0.20.1 requires ~ 16hrs. Is this simulation  time increases expected? 
Thanks

**Comment by Lnaden** [comment]
Well that does look suspicious!

Could you provide the YAML file(s) you are using to run this job? And are you using this on a cluster or locally; parallel or serial?

The structure of the YAML file changed a bit in 0.21.0, but has defaults to make is somewhat compatible with the old version. So my first guess is that there is a default to make each iteration between the two versions unequal, but we would need more info first.

**Comment by nividic** [comment]
@Lnaden Thanks a lot for your help. I have attached the two yaml files related to the different YANK version that I'm using. The files has been taken from the YANK experiment directory between the two runs. The only difference is the update of the yaml syntax between the two YANK versions as you sad. 

[yamls.zip](https://github.com/choderalab/yank/files/2055337/yamls.zip)

**Comment by Lnaden** [comment]
So from this it looks like the constructed `samplers` and `mcmc` moves will be nearly similar based on your `default_X` settings. However, this is the update where `online_analysis` is turned *on* by default. So every 200 iterations, the simulation is halting to do a full batch of analysis. Although that should still not explain the total time spent, especially with that few of states. 

try setting `online_analysis_interval: null` in the mean time. @andrrizzi any ideas on what else could be causing the slowdown?

**Comment by jchodera** [comment]
Could you include your full input files so we can debug further here?

**Comment by nividic** [comment]
@Lnaden @jchodera Hi there, I have attached the link to the yank files required to reproduce my reported issue between the two yank versions 0.20.1 and 0.22.1. In the directories I left the partial yank generated logs (I interrupted the runs after few yank iterations) to show the discrepancy in the simulation time. Hopefully, you will be able to reproduce the problem. Thank you so much for your help. 

https://drive.google.com/open?id=17r3fJ7uwbB7xQEXjQfe7_rf3aAc_VH3o

**Comment by jchodera** [comment]
Apologies for taking so long to look into this, @nividic!

Both 0.20.1 and 0.22.1 end up using replica-exchange, which is going to be much slower than the new `SAMSSampler`. We should move you to over to that as soon as possible.

The major slowdown seems to be due to writing data to the NetCDF file. In 0.20.1:
```
2018-05-31 13:13:55,064 - DEBUG - openmmtools.utils - Storing sampler states took    0.105s
2018-05-31 13:13:55,167 - DEBUG - openmmtools.utils - Writing iteration information to storage took    0.208s
```
but in 0.22.1, this goes way up:
```
2018-05-31 14:22:43,054 - DEBUG - openmmtools.utils - Storing sampler states took  141.595s
2018-05-31 14:22:43,097 - DEBUG - openmmtools.utils - Writing iteration information to storage took  141.639s
```
@Lnaden may have some insight into why this is happening. It *could* be some extra `ncfile.sync()` calls that were added to try to increase storage file integrity in the case of early termination.

Alternatively, is there some way the performance of the attached storage you are using has changed? Is it possible you aren't writing to fast local storage (e.g. SSD) but instead to network-attached storage?

**Comment by jchodera** [comment]
These storage bottlenecks should be eliminated by SAMS.

@Lnaden : What is odd is that the explicit solvent sampler states aren't supposed to be written except every 200 iterations, but the timing for 0.22.1 is still really long:
```
2018-05-31 14:17:14,641 - DEBUG - yank.multistate.multistatereporter - Iteration 2 not on the Checkpoint Interval of 200. Sampler State not written.
2018-05-31 14:19:34,925 - DEBUG - openmmtools.utils - Storing sampler states took  140.284s
2018-05-31 14:19:34,969 - DEBUG - openmmtools.utils - Writing iteration information to storage took  140.328s
```

**Comment by nividic** [comment]
@jchodera The storage was not on a network file system, everything for both yank versions was running locally

**Comment by andrrizzi** [comment]
Hmm. In iterations that are not checkpoints, we do save the sampler states, but only the solute and ions coordinates. Ignoring the solvent , but it looks like the timing for checkpoint and non-checkpoint iterations is roughly the same.

Can you check which atoms are actually saved?
```python
from yank.multistate import MultiStateReporter

reporter = MultiStateReporter('path/to/ncfile.nc', open_mode='r')
try:
    print(reporter.analysis_particle_indices)
    sampler_state0 = reporter.read_sampler_states(iteration=2, analysis_particles_only=True)[0]
    print(sampler_state0.n_particles)
    print(reporter._checkpoint_interval)
finally:
    reporter.close()
```

**Comment by Lnaden** [comment]
The larger iteration chunk sizes is the culprit (we introduced this when we set the iteration chunk size to the checkpoint interval)

The line below is the slow step and cannot be profiled with cProfile for some reason, its not caught by the profiler.

`storage.variables['positions'][write_iteration, replica_index, :, :] = x[:, :]`

That is slow, even though the number of analysis particles is small, its still having to fetch 200x the data chunk from disk to so because we set the iteration chunk size to the size of the checkpoint interval, which is 200 by default. In SAMS this is not so noticeable because of the single replica. In Replica Exchange though, its much more noticeable because we have more replicas and loop over them, calling that same large chunk every time. 

https://github.com/choderalab/yank/blob/master/Yank/multistate/multistatereporter.py#L1561

**Comment by Lnaden** [comment]
I can try to rework the function to only call the NetCDF writing once, that might make it faster independent of the number of replicas.

**Comment by jchodera** [comment]
> That is slow, even though the number of analysis particles is small, its still having to fetch 200x the data chunk from disk to so because we set the iteration chunk size to the size of the checkpoint interval, which is 200 by default. In SAMS this is not so noticeable because of the single replica. In Replica Exchange though, its much more noticeable because we have more replicas and loop over them, calling that same large chunk every time.

Good catch!

If we can't set a different default checkpoint interval for replica exchange, let's just set the default checkpoint interval to 10.

**Comment by Lnaden** [comment]
@nividic I have a partial fix for this issue in the linked PR above. It gets my local time down from about 100 seconds per write to 5 seconds per write. This is not as fast as before (~0.1 - 1s), but there is a balance issue between read and write access times. I have changed the code to reduce the number of calls we make to this slow step, where all the time is gained. 

If you can test this (would have to build locally), or if you think this is sufficient, I can merge this in. If you still need faster, I can spend some more time with the balance issue to make it better.

**Comment by nividic** [comment]
@Lnaden Thanks a lot for all your hard working on the issue. Please go ahead and merge.
