### ISSUE TITLE
Yank report is not correctly generated 

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1037]
After I run a short ABFE calculation I wanted to generate the yank report in .html format by using the command line:

`yank analyze report --store=output/experiments --output results.html`

However, the produced file is not  correctly displayed in different browsers (Safari, Firefox and Chrome) on different operating systems as well (OSX and Linux). The Yank version that I'm using is 0.23.1 and I have attached an example system to reproduce the issue.  

Thanks a lot for your help,

Gaetano

https://drive.google.com/open?id=10ASyiWoU6Y6UWCa9fsfQBz6x9TVO4pPa

**Comment by Lnaden** [comment]
Looking at it now. Should be a quick fix

**Comment by Lnaden** [comment]
@nividic 

This is actually behaving as expected. We had to change the way the output file format is specified because there was no way to infer the format from the output directory if you are using the `-y yaml` instead of `-s directory`. We now have to enforce the user specify what the file format output is though the `--format` flag. The extension is no longer processed from filename.

If you add `--format html` that will give you the result you expect. 

You can also specify `--format pdf` and `--format ipynb` (default, and value set if --format is not specified).

I'm going to leave this open until you let me know this is the issue. I'm also open to using a different default besides Jupyter Notebook if you or others have an opinion.

**Comment by nividic** [comment]
@Lnaden Thanks a lot...that worked...now I should have everything in place for Orion. You can close the case. Have a nice weekend, Gaetano

**Comment by Lnaden** [comment]
Great! Im looking forward to it!. Let me know if anything else comes up!
