### ISSUE TITLE
Yank fails to set Boresch restraints

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1047]
Hi There, I was trying to run Absolute Binding Affinity Calculation on toluene bonded to lysozyme. Unfortunately, I’m having problems selecting the Boresch restraints (I tried Boresch and BoreschPeriodicTorsion). Yank tries to set the restraint and after 100 attempts fails. I’m using Yank 0.23.1 and OpenMM 7.2.2. I have attached the system and all the Yank required files. Let me know if you need further info. Thanks a lot for your help.  

https://drive.google.com/open?id=1MHeolEozUVe_ktsbkxebkEFNcj1EctqT

**Comment by Lnaden** [comment]
Still looking into it, but it looks like the ligand does not have bonds defined in the Topology. Since the Boresch restraint now requires bonded atoms for stability in the restrained virtual plane, it cannot find any bonds, so it fails. I'm looking into why.

**Comment by Lnaden** [comment]
How did you set this system up? When the XML files are loaded back in, there is no bond information stored, so the only bonds which MDTraj's Topology can make are from the standard residue names, which the ligand is not. Since no bonds are tied to the Ligand, no three bonded atoms cannot be targeted for the Boresch-like restraints, hence the error that is thrown.

**Comment by jchodera** [comment]
@nividic: How did you generate your PDB file?

The issue here is that the PDB file you generated is not actually compliant with the [PDB file format](https://www.wwpdb.org/documentation/file-format) and is missing critical information on the bonds between ligand atoms. According to the format, connectivity for standard amino acids and waters is implicitly defined, but you *must* specify `CONECT` records for any other residues. Your ligand has no `CONECT` records defining the bonds, so there is no way for YANK to interpret the topology of your ligand correctly---the information just isn't there.

Can you generate a compliant PDB file that has `CONECT` records?

**Comment by Lnaden** [comment]
Some more debugging. Neither the MDTraj nor the OpenMM `Topology` objects have records for bonds between the ligand atoms, however, the final OpenMM `System` does have values for the bond. 

The XML appears to have `HarmonicBondForce` information (force constants and what not), so the final system is correct, but that information is not parsed by the `Topology` objects where we derive connectivity from; those only use the PDB file. It would be ill advised to derive a Topology from an OpenMM System due to the fact that you could have a "bond" defined by multiple `Force` objects, and its impossible to distinguish chemical bonds from virtual/alchemical bonds. 

So I think the "quick" fix is to do what @jchodera suggested by adding `CONECT` records to the PDB file for the ligand to get the correct Topology object. I'm not sure if there is a better solution at the moment.

**Comment by nividic** [comment]
@Lnaden @jchodera I'm sorry for my late reply. I made the required changes to produce the correct pdb file with the CONECT section for the ligand and everything seems to work now. Thank you so much for your help. You can close the issue.

**Comment by Lnaden** [comment]
Great to hear!

**Comment by jchodera** [comment]
@Lnaden : Should we add some error checking that would check whether the ligand has no bonds if restraint imposition fails? That might produce a helpful error message in this (probably common) failure case.
