### ISSUE TITLE
Have yank analyze report --output option create directory if it does not yet exist

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1055]
Instead of refusing to generate output files, why don't we have the `--output` option create the directory if it doesn't yet exist?

**Comment by jchodera** [comment]
Here's some example output illustrating the current behavior:
```
[chodera@lilac:yank]$ yank analyze report --yaml xchem.yaml -o report
Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.23.2', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/commands/analyze.py", line 124, in dispatch
    "analysis".format(args['--output']))
ValueError: report is not a directory, which is required when specifying a YAML file as a source for analysis
```

**Comment by Lnaden** [comment]
I made that choice on purpose. Because the choice of `-s` vs. `-y` changes the behavior of the `-o` flag from writing a single target file vs writing to an actual directory, I did not want users to accidentally overwrite exiting files with a directory, or writing to a directory called something like `report.html` and then they think its an HTML file. So by forcing the user to target an existing directory, they are required to understand that the `-o` functionality has changed.

**Comment by jchodera** [comment]
I'm not sure I understand---there is no danger of overwriting an existing file with a directory if the directory is only created if it does not yet exist.

**Comment by Lnaden** [comment]
Fair point, but then that brings up the second one. Users may get confused and think they are writing to a single file (of filename template).

**Comment by jchodera** [comment]
I'm pretty sure they will notice when they end up with a directory full of files. And we can solve this with additional documentation in the CLI help.

**Comment by abradle** [comment]
I agree with @jchodera I think it would be useful and clear.
