### ISSUE TITLE
Unable to open host file when running build_mpirun_configfile 

### ISSUE THREAD

**Issue by agreen69** [choderalab/yank#1072]
Hello, I am running the following command to run the BRD4 benchmark dataset using replica-exchange and harmonic restraints on my local cluster. Here is the command and PBS file that I run: 
```bash
#!/bin/bash
#PBS -l qos=std 
#PBS -q gpu 
#PBS -N test  
#PBS -l nodes=1:ppn=32,walltime=26:00:00
#PBS -e apo_md.err
#PBS -o apo_md.out


cd $PBS_O_WORKDIR


module load cuda/8.0
export OPENMM_CUDA_COMPILER=/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cuda/8,0/centos7.2_binary/bin/nvcc
export LD_LIBRARY_PATH=/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cuda/8.0/centos7.2_binary/lib64:$LD_LIBRARY_PATH
export mpirun=/home/a12/miniconda3/bin/mpirun
export yank=/home/a12/miniconda3/bin/yank

build_mpirun_configfile "yank script --yaml=repex-twostage-harmonic-auto.yaml"
mpiexec.hydra -f hostfile -configfile configfile
```
And here is the error message I get after submitting the job from build_mpirun_configfile.py: 
```
Traceback (most recent call last):
  File "/home/a12/miniconda3/bin/build_mpirun_configfile", line 6, in <module>
    sys.exit(clusterutils.build_mpirun_configfile.main())
  File "/home/a12/miniconda3/lib/python3.5/site-packages/clusterutils-0.3.1-py3.5.egg/clusterutils/build_mpirun_configfile.py", line 248, in main
  File "/home/a12/miniconda3/lib/python3.5/site-packages/clusterutils-0.3.1-py3.5.egg/clusterutils/build_mpirun_configfile.py", line 258, in figure_out_manager
  File "/home/a12/miniconda3/lib/python3.5/site-packages/clusterutils-0.3.1-py3.5.egg/clusterutils/build_mpirun_configfile.py", line 134, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/var/spool/torque/aux//401756.or-condo-pbs01gpu'
```

**Comment by agreen69** [comment]
Any suggestions for debugging?

**Comment by jchodera** [comment]
It looks like our [`clusterutils` tool](https://github.com/choderalab/clusterutils) is trying to interpret the file that allocates nodes and GPUs to your batch queue job, and while your queuing system [sets the `PBS_GPUFILE` environment variable](https://github.com/choderalab/clusterutils/blob/master/clusterutils/build_mpirun_configfile.py#L134), the file is not actually accessible by the node that the job starts on. This would appear to be due to a queuing system misconfiguration, which I'm afraid we can only be of limited help with.

Here's what I would suggest:
* In your batch queue script, first comment out these lines:
```
build_mpirun_configfile "yank script --yaml=repex-twostage-harmonic-auto.yaml"
mpiexec.hydra -f hostfile -configfile configfile
```
* Add the following debug info
```bash
# which host are we on?
hostname
# print all environment variables
env
# print just the `PBS_GPUFILE` environment variable
echo $PBS_GPUFILE
# check that file exists
ls -l $PBS_GPUFILE
# print its contents
cat $PBS_GPUFILE
```
You will have to ensure that your batch queue system is correctly creating `$PBS_GPUFILE` before our tools will work.

**Comment by agreen69** [comment]
Yep file not found. Seems to be a problem with the queue system. Thanks so much!

**Comment by andrrizzi** [comment]
Closing now, but feel free to reopen if you still have problems!
