### ISSUE TITLE
pymbar-3.0.0 is not compatible with Yank

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#236]
Hi there,

I installed the latest version of pymbar (3.0.0) downloading it from GitHub (master branch). When I was running the analysis module to compute the binding affinities an error was raised (ValueError: too many values to unpack) in the module analyse.py line 188 in mbar.getFreeEnergyDifferences() . In order to fix the error I had to install a previous version of pymbar (pymbar2.X) from GitHub. Therefore probably some bugs were introduced in the new version of pymbar with Yank.

Cheers,

Gaetano

**Comment by Lnaden** [comment]
As a workaround, if you change the line in yank from `(Deltaf_ij, dDeltaf_ij)` to `(Deltaf_ij, dDeltaf_ij, Theta_ij)` it should let yank work with pymbar-3.0.0-dev0.

The error is from `getFreeEnergyDifferences()` returning the Theta_ij matrix along with the Deltaf_ij and dDeltaf_ij matrix. Analyze.py expects only the later of those options. Since pymbar now returns None for either dDeltaf_ij or Theta_ij when they are not computed, any call which assigns 2 variables will not be able to correctly assign the 3 returns. 

I know in older versions of pymbar, the compute_uncertainty and return_theta keywords only appended to the return list when True. I'm assuming that the default of returning None for all three returns was done so there was consistent indices, i.e. `return_theta=True` and `compute_uncertainty=True` returned `(Deltaf_ij, dDeltaf_ij, Theta_ij)` whereas doing just `return_theta=True` gives `(Deltaf_ij, Theta_ij)`. This may be a better discussion for the pymbar repo to determine what the standard returns should be going forward, or at the very least how to invoke the function in other programs.

**Comment by jchodera** [comment]
Thanks!

For now, I've updated the conda recipes to use `pymbar 2.1beta0`, but I'll keep this issue open to remind us to update for the new `pymbar 3`.

**Comment by jchodera** [comment]
Created a new issue: #243.
