### ISSUE TITLE
run on multiple gpus

### ISSUE THREAD

**Issue by dprovasi** [choderalab/yank#269]
I'm trying to run on one node with multiple gpus. 
I set CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 and the gpus are not in exclusive compute mode, and I submit with with
mpirun -np 8 yank run --store=output --verbose  --platform=CUDA --mpi
but all processes are running on the same card. 
Do you have any advice on where to look to fix this?

**Comment by jchodera** [comment]
Currently, the MPI mode of `yank` has every MPI process use the default GPU.  This is because different batch queue systems and `mpirun` launchers have different ways of allocating GPUs to MPI processes, and we couldn't find a general solution that would allow multiple processes to run on arbitrary GPUs across different nodes.

The way we deal with this (using the `hydra` `mpirun` version that comes with the MPI [conda package](http://conda.pydata.org/docs/) installed as a prerequisite for `mpi4py` is to use a simple script to build an `mpirun configfile` that sets `CUDA_VISIBLE_DEVICES` correctly for each MPI process.  This script can be obtained [here](https://github.com/choderalab/clusterutils) or installed [via `conda` from binstar](https://binstar.org/omnia/clusterutils).

An example of this appears in the [`p-xylene-implicit` script `run-torque.sh`](https://github.com/choderalab/yank/blob/master/examples/p-xylene-implicit/run-torque.sh#L48-L49).  In this example, the `$PBS_GPUFILE` generated by Torque/Moab is read and processes to generate a `configfile` that is passed to `mpirun` to properly pair MPI processes with `CUDA_VISIBLE_DEVICES` masks.

I'll make a note to update the docs to make this process clearer.  Thanks for pointing it out!

**Comment by dprovasi** [comment]
thanks! I'm using LSF, so I don't have a `$PBS_GPUFILE` but it seems I can run on multiple cards using a `configfile` as follows
```bash
-host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 0 yank run --store=output --verbose  --platform=CUDA --mpi
-host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 1 yank run --store=output --verbose  --platform=CUDA --mpi
-host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 2 yank run --store=output --verbose  --platform=CUDA --mpi
-host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 3 yank run --store=output --verbose  --platform=CUDA --mpi
```
it's not very elegant, but is seems to work for a single node. I'll go through the examples and make sure I get the right results. 
Could you comment on the optimal choice of MPI tasks? Should I use one task per gpu, irrespective of the number of replicas (this seems to be the case in the [`p-xylene-implicit` script `run-torque.sh`](https://github.com/choderalab/yank/blob/master/examples/p-xylene-implicit/run-torque.sh#L48-L49)?

**Comment by jchodera** [comment]
Hopefully you can at least generate that `configfile` automatically with a script!

> Could you comment on the optimal choice of MPI tasks? Should I use one task per gpu, irrespective of the number of replicas (this seems to be the case in the p-xylene-implicit script run-torque.sh?

For maximum throughput, you should use one MPI process per GPU.  There may be some efficiency gain in running with multiple processes per GPU (especially on very small systems that may not consume all GPU resources), but we haven't extensively benchmarked this.

I'm afraid we also don't have a benchmark suite yet---just some examples we're working on as illustrations of how to use YANK.  More information and a real benchmark suite is coming soon!

Do make sure you run `yank selftest` to make sure at least the nosetests and doctests pass on your hardware!

**Comment by jchodera** [comment]
This should have been addressed by the `build_mpirun_configfile` tool.

**Comment by lx18233184051** [comment]
> thanks! I'm using LSF, so I don't have a `$PBS_GPUFILE` but it seems I can run on multiple cards using a `configfile` as follows
> 
> ```shell
> -host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 0 yank run --store=output --verbose  --platform=CUDA --mpi
> -host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 1 yank run --store=output --verbose  --platform=CUDA --mpi
> -host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 2 yank run --store=output --verbose  --platform=CUDA --mpi
> -host filizm02-3 -np 1 -env CUDA_VISIBLE_DEVICES 3 yank run --store=output --verbose  --platform=CUDA --mpi
> ```
> 
> it's not very elegant, but is seems to work for a single node. I'll go through the examples and make sure I get the right results.
> Could you comment on the optimal choice of MPI tasks? Should I use one task per gpu, irrespective of the number of replicas (this seems to be the case in the [`p-xylene-implicit` script `run-torque.sh`](https://github.com/choderalab/yank/blob/master/examples/p-xylene-implicit/run-torque.sh#L48-L49)?

could you please explain more?
