### ISSUE TITLE
Sign box correction explicit solvent

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#299]
I believe the sign of the standard state correction for the box volume should be minus, written as it is
(yank.py line 302)

**Comment by jchodera** [comment]
I think you're right!

I wonder if there's a good test we can add for a simple system to verify that we have the sign correct.  What about a system with two Lennard Jones spheres, where one of the spheres is decoupled as a "ligand"?

**Comment by davidlmobley** [comment]
@nividic, this is the issue I mentioned.

@jchodera - we are thinking about getting involved with testing here. The LJ test system you mentioned should work. We were also thinking of running a lysozyme example in explicit solvent, unless you've done that already?

Though, with respect to this particular sign issue it ought to be obvious through thinking through the direction. The standard state correction is the free energy of releasing the noninteracting, restrained ligand to the full volume, and (assuming you use my/Gilson's convention and your restrained volume is less than the standard volume) is always a positive number. This is an entropic contribution - basically the larger this number is, the less entropy your molecule had when bound/restrained, and the more it gets back by being released. This opposes binding (since losing a lot of entropy on binding is unfavorable) so it should be added in that direction - i.e. if it's a positive number you add it to the calculated binding free energy. (The caveat of course is that if your restrained volume is large enough this might actually be a negative number, so in that case - which seems odd - it could actually contribute favorably to binding.)

**Comment by jchodera** [comment]
Is there a simple way to add a unit test for this correction?  Perhaps I just see if it recapitulates the free energy difference expected from two boxes of known size?

**Comment by luirink** [comment]
Isn't it the other way around? The free energy of restraining to a smaller volume (so going from standard volume to restraint) is positive? In case the restraint volume is smaller than the standard volume?

And this, indeed, should be added to the binding free energy, in that case. In the analysis this is actually subtracted, and therefore the free energy going from restrained to standard state volume should be used (and therefor. However, since it is substracted e the sign should be changed). A check like the LJ test system should work indeed.

**Comment by davidlmobley** [comment]
>Isn't it the other way around? The free energy of restraining to a smaller volume (so going from standard volume to restraint) is positive? In case the restraint volume is smaller than the standard volume?

Yes, I actually said the free energy of releasing is always a positive number, but meant that the free energy of restraining is always a positive number. But the end conclusion was that it should be added - there we agree. Sorry about the confusion. 

>Is there a simple way to add a unit test for this correction? Perhaps I just see if it recapitulates the free energy difference expected from two boxes of known size?

Yes, that should work.

**Comment by jchodera** [comment]
See #305.
