### ISSUE TITLE
Use logging for logging

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#3]
I think we *should* be able to use logging to control the verbosity level without having to pass around `verbose` arguments everywhere.

It might be possible to make this work with MPI as well: https://github.com/jrs65/python-mpi-logger

**Comment by pgrinaway** [comment]
What is the status of this?

**Comment by andrrizzi** [comment]
I also find it useful to save the log message in a file to be able to go back and check when something goes wrong. Right now using "yank run -s STORE -v > yank.log" doesn't work perfectly because the logging.debug() are printed on stderr while print() uses stdout. The logging module can print on the screen and save the messages in a file at the same time and with different levels. An alternative implementation that takes care of this issue and saves also the result in a file:

```python
import logging

class Yank:
    def __init__():
        ...
        # Configure root logger
        logging.basicConfig(filename='yank.log', level=logging.DEBUG)
        stdout_handler = logging.StreamHandler(sys.stdout) # or sys.stderr if you prefer
        stdout_handler.setLevel(logging.INFO) # the level here is set according to the verbose arg
        logging.getLogger().addHandler(stdout_handler)
        ...
```
after the root logger has been configured the other loggers inherit the configuration so with the example above
```python
#in alchemy.py
logger = logging.getLogger(__name__)
logger.debug('debug test')
logger.info('info test')
```
save both the strings "DEBUG:yank.alchemy:debug test" and "INFO:yank.alchemy:info test" in the file yank.log, but only "INFO:yank.alchemy:info test" is printed on stdout.

Maybe once this is implemented all the print() calls could be replaced by logging.info()?

The log is always appended to the existing file so it should probably be deleted at startup or with "yank cleanup".

**Comment by pgrinaway** [comment]
+1

**Comment by andrrizzi** [comment]
I have implemented this in my branch since I'm using it for debugging.

Right now the logging configuration is command-based. Only "run" and "prepare" save the log file, unless run is called with --mpi in which case the file is not saved and verbose is set to false.

I'm going to test it a little bit more while I'm using it before submitting a pull request.

**Comment by jchodera** [comment]
This is great, thanks!  Please do submit a PR!  It's easier to comment on your modifications that way.

You can mark it as "[WIP]" to denote that you aren't quite ready to merge yet.

**Comment by andrrizzi** [comment]
I think there's nothing else we need to do about this. Closing.
