### ISSUE TITLE
Simplifying options handling

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#314]
The YAML framework introduced by #310 is fantastic, but it seems like we might be able to simplify how we handle options to make things a little simpler.  The `yank.util.YankOptions` object, for example, currently stores 
* default options
* CLI options
* YAML options
* runtime options

and has to correctly juggle precedence among all of these.

Is there some way we can refine this somehow by allowing options to be specified by either YAML, command-line, or default initialization and just making sure to read these in the correct order?

 Perhaps we can brainstorm how each module can keep a central list of options that it wants to manage, while still allowing us to validate that the options specified by the user are valid and have the correct units.  Is there a simple way to do this?

**Comment by bas-rustenburg** [comment]
How about collecting every set of options separately into `dict`s and then combining those in one, consistent order of preference that we can also add to the documentation:

Say, 
* start with default options dictionary for every module,
* override keys by yaml options that were added,
* replace keys by cli options,

not sure what "runtime" options means. Can you change options during the middle of a run?

Then, at the end, validate the `dict` to make sure options are correct and compatible.

You can store the options as a yaml input file, similar to what gromacs does, if you want to manually  validate, or easily rerun with the same options.

**Comment by andrrizzi** [comment]
I agree that the options in Yank aren't currently handled very well. I also don't like too much that we pass the options as an argument to each function that needs them. I'm not sure though how the independent repex and alchemy repos will handle options when they will be integrated, so we should probably come up with a design that can be easily shared among all the repos.

Keeping the runtime and YAML options separated may be useful for people that want to use Yank through its API. For example, say you want to run multiple Yank experiments from a single script with different options. You can use the API to load a different YAML file for each experiment, or start from a basic YAML file and hardcode the few options that you want to tweak for each experiment. To do this, Yank needs to remember which were the default options and which the ones given through YAML. I agree that we can merge default and command line options while parsing them since they won't change during a single run, but I would keep YAML and runtime options in a separated dictionary in memory and handle their precedence.

**Comment by bas-rustenburg** [comment]
> but I would keep YAML and runtime options in a separated dictionary in memory and handle their precedence.

Could you clarify what you mean by runtime options? Does yank take input from `stdin` during the run?

**Comment by andrrizzi** [comment]
Sure, sorry it's not clear, I couldn't find a better name. By runtime options I mean those that are hardcoded in your Python script (and that are not default options). For example, if you want to check the effect of the integration time step on the simulation, you can do something like
```python
options = load_yaml()  # this one contains timestep = 1.0*femtoseconds
run_simulation(options)
options['timestep'] = 2.0*femtoseconds  # this one I call a runtime option
run_simulation(options)
```
I hope this clarifies a bit.

**Comment by jchodera** [comment]
Thanks, everyone!

OK, it sounds like we're settling on something like this:

* Each class has some way to organize and access user-selectable "options"
in a uniform way
* Each class also specifies default options
* We may have a YAML file that overrides any of these default options
* In addition, users may want to specify additional override options that
take precedence either via the command-line or through an 'options' object
in the API.  This last part I'm not entirely sure about---the user may want
to build the options object in their own way, and we may not want to "bake
in" YAML file handling to the main Yank classes, instead keeping this in
some sort of command-line driver class.  (We may later want, for example,
JSON instead for web stuffs).

**Comment by andrrizzi** [comment]
So, if I understand correctly, we want to make it possible for the API user to decide the precedence of the various options. I agree, I didn't consider that.

For validation, I see three solutions (just brainstorming here)

1. The most elegant solution would probably be to let each class verify the options it manages, but if we merge them into a single ```dict``` we can't tell the user if the error was in the yaml/json file or in the CLI.
2. We could let the user set the precedence order in ```yank.util.YankOptions```. This way we can validate the options inside the Yank classes and trace back where was the error. The problem with this is a more complicated API.
3. Alternatively we can validate before merging which means we have to equip the API user with some utility functions to help him in the task. This has a simpler interface but validation is not performed automatically so the user is responsible for this.

**Comment by bas-rustenburg** [comment]
> The most elegant solution would probably be to let each class verify the options it manages, but if we merge them into a single dict we can't tell the user if the error was in the yaml/json file or in the CLI.

I'm a fan of the single dict approach. We can print out the final compilation of options by default as a new yaml file - adding an option to not print if undesired -, and the user could compare those with their input. This would be good for reproducing a calculation without needing to dig into your shell history, and can also be used to generate a template input file. 

> We could let the user set the precedence order in yank.util.YankOptions. This way we can validate the options inside the Yank classes and trace back where was the error. The problem with this is a more complicated API.

I feel like making precedence order variable would be a bad idea for reproducibility and would potentially confuse users that use it differently. Some people may even make the wrong assumptions about precedence and make errors because of this. 

> * Each class also specifies default options

Should this be within the class, or centralized? We can store the default options outside of it. 

Here is one design idea:
* a class shouldn't be able to operate unless all options it needs are explicitly passed. 
* We could explicitly pass the options to each yank class by using (**kwargs) and unpacking the options object.
* It should raise an error if it doesn't receive all options it needs, or has conflicting options. 

That would make things less ambiguous in my opinion. I wouldn't do any options handling within classes, other than reading and validating them.

**Comment by andrrizzi** [comment]
> We can print out the final compilation of options as a new yaml file
Just a clarification here. Currently ```yank.utils.YankOptions``` implements the ```dict``` interface so we could do this in both cases.

**Comment by andrrizzi** [comment]
I'm having second thoughts about handling options with a centralized solution. If in the future we want to do something like
```python
yank = Splash()  # specialization of Yank class for solvation energy
yank.alchemy = UserDefinedAlchemy()
yank.repex = UserDefinedRepex()
```
each of these classes may want to handle slightly different sets of options or have different default values or validation procedures. I feel that adopting a centralized solution may results in an unnecessary complicated code.

So, trying to sum up the previous comments and our last meeting, what about something like this
* The driver class puts together a nested ```dict``` in the form
```python
options = {'yank': {'minimize': False, 'platform': 'CPU'},
           'repex': {'nstep_per_iteration': 2500},
           'alchemy': {'path': [1.00, .8, .6, .4, .2, 0]}
           }
```
* The classes Yank, Repex and Alchemy all implement a ```validate_options()``` method
```python
class Yank:

    def __init__(self, store_directory):
        self.default_options = {'minimize' = False, 'platform' = None}
        self.alchemy = DefaultAlchemyClass()
        self.repex = DefaultRepexClass()

    def validate_options(self, options, check_mandatory=True, check_unknown=True):
        # call also self.repex.validate_options() if options['repex'] is defined
        # raise exception if unknown option
        # raise exception if missing mandatory options
        # process/validate option types
        # return dict containing processed options

    def create(self, phases, ..., **kwargs):
        self.options = validate_options(kwargs['yank']) + self.default_options
        alchemical_states = self.alchemy.get_alchemical_states(kwargs['alchemy'])
        self.repex.create(kwargs['repex'], alchemical_states)

class AnyAlchemyClass:
    default_options = {...}
    def validate_options(options, check_mandatory=True, check_unknown=True):
        # same as above

class AnyRepexClass:
    default_options = {...}
    def validate_options(options, check_mandatory=True, check_unknown=True):
        # same as above
```
* a public ```validate_options()``` method means that a driver class can inform the user about where errors are. For example
```python
yank = Yank()
cli_options = get_cli_options()
yaml_options = get_yaml_options()

try:
    yank.validate_options(cli_options)
except Exception as e:
    raise Exception('Error CLI options: ' + str(e))

try:
    yank.validate_options(yaml_options['yank'])
except Exception as e:
    raise Exception('Error YAML options: ' + str(e))

final_options = merge_options(cli_options, yaml_options)
yank.create(..., final_options)
```
would something like this be ok? Suggestions? Of course something similar can be implemented also with an *un*-nested ```dict``` if you don't like the nested structure.

**Comment by jchodera** [comment]
Thanks for working through this!  This is incredibly helpful.

**I like the idea of having each class have a `validate_options` method.**  This cleanly separates the responsibility for option checking, and makes it very easy to add new classes or subclasses without having to touch existing code.  This could even be a mix-in if we wanted to make it easier to enforce a common interface, but that also could enforce unwanted dependencies between packages that are best left to duck typing.

**I'm less keen on separating the options into CLI and YAML options by splitting them into separate dicts.** I think this adds unnecessary complexity.  I think a more clever way to handle this might be to have an error in options raise an `OptionError` exception that also contains some metadata about the problematic option and where the exception was raised. If we did this, then we could later add an exception handler to the command-line interface that examines both the command-line and the YAML file to figure out where the problematic option was specified (e.g. line number and context).  This might deserve some more thought, though.

**Comment by andrrizzi** [comment]
> I'm less keen on separating the options into CLI and YAML options by splitting them into separate dicts.

Sorry if this wasn't clear. I wasn't suggesting to split them into separate dicts, and the API I'm proposing takes a single dict as input. I was just pointing out that at some point in the code those options *will have* to be contained into two dicts (simply because the CLI options come from ```docopt``` and the YAML options come from ```YamlBuilder```) and we can exploit this to inform the user about the source of eventual errors.

I guess a better way to write those two lines would be
```python
cli_options = process_docopt_args(docopt_args)
yaml_options = YamlBuilder('yamlfile.yaml').get_options()
# here the driver class merges the two dictionaries into a single one to feed to Yank
```
I used ```cli_options``` and ```yaml_options``` here because they are an easy example since that's what we'll have to deal with, but I'm not proposing to "bake" them into Yank. A third-party application that uses Yank API would be able to build the final (single) options dict in an entirely differently way (e.g. from JSON or its own command interface arguments).

I hope this clarifies a little. Or it's me that I'm missing some important point?

**Comment by andrrizzi** [comment]
This was implemented in the last PR. Closing for now, but feel free to reopen in case you have new suggestions.
