### ISSUE TITLE
yank.py deepcopy

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#322]
Does it make any sense to make a deepcopy and give it the same name? I suppose nothing really happens then. (yank.py  line 273)

 # Make a deep copy of the reference system so we don't accidentally modify it.
reference_system = copy.deepcopy(reference_system)

**Comment by jchodera** [comment]
If the user passes a `reference_system`, only a shallow copy (like a reference or pointer) is passed in.  Modifying it (by accident) will modify the original system, which may have unintended consequences.

Instead, we make a deep copy so that the local variable `reference_system` points to a completely independent copy.  We are then free to make changes to the `System` object this points to without causing unintended changes to the `System` object the user passed in.

Incidentally, `deepcopy` for `Force` objects was broken in the development version of OpenMM due to a bug introduced after OpenMM 6.3, and was only fixed yesterday:
https://github.com/pandegroup/openmm/pull/1211

This had prevented the new [`alchemy`](https://github.com/choderalab/alchemy) module from working.
