### ISSUE TITLE
Add support for non-TIP3P explicit solvent models

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#378]
Do we currently support explicit solvents other than TIP3P? If so, how are they specified?

**Comment by andrrizzi** [comment]
Right now only TIP3P. If we want to support other kinds, we need to decide about the syntax (pretty easy) and create a mapping between OpenMM and Amber solvent names for future compatibility.

**Comment by jchodera** [comment]
Not sure if we need this for 1.0 or now. Depends on how the paper shapes up.

**Comment by Lnaden** [comment]
Probably early post 1.0 issue unless we can change the YAMLBuilder to accept the other types of LEaP auto-solvent boxes. There should be access to SPC-E, TIP3P, TIP4P-EW, and TIP5P boxes.

**Comment by Lnaden** [comment]
Wanted to add some thoughts to this while I am thinking of it.

Adding support for the solvents which have leaprc files would not be too hard. However, adding supports for some more obscure solvents such as `tip4pfb` will be harder since we have to load the atom names and then the frcmod to access those files. We could just not support those water models, but we did at one point when the `yank prepare` CLI was still a thing.

**Comment by andrrizzi** [comment]
I'm working on this now. I'm planning to add support only for solvents that are supported both by openmm and tleap, and use the openmm naming scheme. This means we'd support `tip3p`, `tip3pfb`, `tip4pew`, `tip5p`, `spce` (in leap this should be `SPC`). The syntax would be:
```yaml
solvents:
  tip3p-water:
    nonbonded_method: PME
    clearance: 15*angstroms
    solvent_model: tip4pew
```
any suggestion before I tackle this?

**Comment by andrrizzi** [comment]
Question: should we have a default value for `solvent_model`? If yes, which one?

**Comment by jchodera** [comment]
This looks great!

I'd recommend tip4pew as default.

**Comment by Lnaden** [comment]
I would be for a tip4p-EW or better model

**Comment by andrrizzi** [comment]
Ok!
