### ISSUE TITLE
Add test.sh test driver scripts to all examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#382]
We need to add `test.sh` scripts to each example so that automated testing will catch any issues.

cc: https://github.com/choderalab/yank/issues/381

**Comment by andrrizzi** [comment]
Sorry if I don't understand, but what's the advantage of adding `test.sh` files instead of just running the currently present `run.sh` with a lower number of iterations?

I think you removed the `test.sh` files with [this commit](https://github.com/choderalab/yank/commit/c3566477b2773bc705ffeb6697769b412d4628bb), although I wasn't in the lab so I don't know what was the rationale.

**Comment by jchodera** [comment]
We're just going to use travis tests for now.
