### ISSUE TITLE
Question: polar hydrogens get a sigma of 1?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#612]
I'm seeing a log/warning message for particles with sigma=0 (i.e. AMBER-style polar hydrogens) that charged particles automatically get a sigma of 1 angstrom if they have a radius of zero. Have you guys checked whether this matters? Naively, I would guess that this would have an impact on computed properties for molecules containing polar hydrogens.

**Comment by Lnaden** [comment]
That is more of an OpenMM implementation issue. OpenMM cannot run with sigma=0 since that causes a crash when computing two particles of sigma=0. However, if epsilon = 0, then the particle is skipped over for the Lennard-Jones calculation. The logger should actually tell you what the epislon is. If its non-zero, then that particle will change the results. We assume if you are feeding it in hydrogens with sigma=0, epsilon is also 0, but its a nonfatal warning.

If q == 0, then it will also skip electrostatics, but those hydrogens typically are not.

**Comment by davidlmobley** [comment]
Ah, I see. Since epsilon = 0 in these cases it doesn't end up mattering. Thanks.
