### ISSUE TITLE
For a series of mixed solvent systems, I have to minimize outside of Yank to avoid crashes

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#643]
I've been troubleshooting a series of cases (I mentioned in passing previously) where I have systems set up via `packmol` (in our `SolvationToolkit`) which I can't simulate in Yank without them crashing as soon as I begin dynamics. *However*, if I add a minimization in OpenMM prior to going into Yank (without perturbing the system!), everything works fine. I am attaching input files to reproduce.

These are systems which always minimize fine in GROMACS for us without issue, but apparently Yank is having trouble minimizing them for some reason. Originally we thought perhaps it was a box vector issue, but I've checked and the box vectors and periodicity seem to be handled correctly. So as far as I can tell it really seems to be an issue with how Yank is minimizing (at least, if I add an "outside of Yank" minimization as a standard procedure in my runs, I avoid these crashes entirely). 

I haven't tracked back through the code to see how the minimization Yank is doing is different from what I'm doing in OpenMM outside of Yank, but perhaps you guys will have insights. We ARE running with openmm 7.1. 

`gaff_in_yank_gromacs_clean` is a clean setup I run which invariably crashes; `gaff_in_yank_gromacs_clean_minfirst` is a setup which adds minimization (see `minimize.py` there) first before running Yank. There is a `run_1.sh` shell script in each directory which does the run on our queueing system. 

One perhaps important note: Systems coming out of `packmol` are typically less well packed and under greater forces (and thus in greater need of minimization) than typical systems we might solvate in a pre-equilibrated box of water (e.g. systems from `tleap` or other mechanisms, I would guess), so this is probably a more stringent test of whether minimization is adequate than most systems you've looked at.

[gaff_in_yank_gromacs_clean.tar.gz](https://github.com/choderalab/yank/files/798004/gaff_in_yank_gromacs_clean.tar.gz)
[gaff_in_yank_gromacs_clean_minfirst.tar.gz](https://github.com/choderalab/yank/files/798005/gaff_in_yank_gromacs_clean_minfirst.tar.gz)

**Comment by andrrizzi** [comment]
Thanks for the input files, this helps a lot. I'll try to figure out what's happening over the weekend.

**Comment by andrrizzi** [comment]
I checked the input files. Yank uses the same minimization of your external script with a lower tolerance of `1.0 * unit.kilojoules_per_mole / unit.nanometers`. The line is [here](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L1385-L1387).

From the log files I see that the yank minimization of the fully interacting state brings the energy
- from  `807189431285.938 kT` to `5248.397 kT` *without* the external minimization.
- from `22423811.766 kT` to `-2147.948 kT` *with* the external minimization.

I tried to further lower the tolerance with
```yaml
options:
    minimize_tolerance: 0.1*kilojoules_per_mole/nanometers
```
which somewhat improved the situation, but I still got NaNs.

So it looks like the alchemically perturbed system (which currently misses the Ewald reciprocal space energy component) does affect the path of the local minimizer.

@jchodera @Lnaden what do you think about adding an extra minimization of the unperturbed system inside `Yank`? This may solve this problem and increase the overall speed of the minimization step a lot since most of the degrees of freedom will be already close to the minimum when `repex` will minimize each replica.

**Comment by davidlmobley** [comment]
Thanks for verifying this. I spent rather a lot of time tracking this down, sadly. 

In this case, adding a minimization of the unperturbed system seems smart and like it might actually result in a net speed *benefit* since then your minimizations at the individual lambda values would go faster. So, it sort of seems like a no brainer.

However, I worry about the issue of the path just being *different*. Specifically, maybe this isn't a general fix and rather just an issue of a minimizer getting stuck on one landscape but not stuck on a slightly different landscape, and maybe sometimes you would have the opposite issue. (I once had this issue so much with the GROMACS energy minimizer (systems might get stuck, or minimize on one architecture but not another, etc.) that I wrote a "tweak" function in Python that would identify systems which got stuck in minimization, go in and randomly perturb coordinates of atoms with the largest forces on them by a few tenths of an angstrom, and then try again. Everything would ultimately get un-stuck and minimize properly, but it was sort of a horrifying solution.) 

On the other hand, it seems like having two cracks at the minimization (as it were) might be reasonably likely to help more than it hurts, since even if you get stuck in the first minimization you've still got another chance (in the minimization at individual lambda values) to get un-stuck, whereas if you minimize only at individual lambda values you only have the one chance...

**Comment by davidlmobley** [comment]
Were there any thoughts on this?

**Comment by davidlmobley** [comment]
Were there any thoughts on this?

**Comment by jchodera** [comment]
I'm still surprised that we end up getting `NaN`s that we cannot recover from even with the separate initial minimization of each alchemical state.

Since we want this to be robust, I'd suggest we consider the following:
* **Initial minimization of the fully-interacting system.** As @davidlmobley notes, even though this is done serially, it could speed up the minimization of all alchemical states.
* **More aggressive initial minimization.** I hate to suggest this because minimization currently takes so long, but it may be necessary to minimize `NaN`s.
* **Explicit equilibration stage with small timestep and high collision rate.** The most helpful thing for relaxing poor initial structures is likely equilibration with a high collision rate (90/ps) and small timestep (0.1 fs).
* **Faster/better minimizers.** The FIRE minimizer may solve multiple problems for us, since it is able to climb over some small barriers. Minimizers that avoid converging to saddle points may also help.
* **Better NaN recovery.** I'm surprised our Langevin restart attempts don't help as much as I would have expected. We could add in a more robust scheme where, if we detect we've hit a few NaNs, we reduce the timestep and increase the collision rate and try again until things stop failing. At least during an equilibration phase, this may serve to clean up problems. It may even allow us to avoid minimization altogether and substitute it with just a more clever fallback scheme for cleaning up poor initial structures with heavily thermostatted dynamics.

**Comment by andrrizzi** [comment]
I plan to add the preliminary minimization of the reference system as part of the big changes I'm doing to make the API more flexible. It should be merged to the master branch in about a week if that's acceptable.

**Comment by davidlmobley** [comment]
Sounds great, @andrrizzi .

**Comment by davidlmobley** [comment]
Any updates on this?

Thanks.

**Comment by andrrizzi** [comment]
Sorry, things took longer than I expected. I've just finished implementing this, but it'll take another couple of days before I can complete testing and merging to master.

**Comment by andrrizzi** [comment]
@davidlmobley just an update. The new engine that includes the preliminary minimization in the reference state is currently ready and validated on few solvation/binding simulations in the branch `fix-development-tests` if you are in a hurry. Merging to master (and pushing of the corresponding `dev` version on anaconda) is currently blocked only by the release of `openmmtools 0.9`, but I think this should happen very soon (probably by tomorrow).

**Comment by andrrizzi** [comment]
@davidlmobley this is now merged to master. We haven't made an official 0.16 release but you can install it and test the new solution from the source code. Let me know if you also need a conda `yank-dev` version.

Closing this for now, but feel free to reopen in case you run into the same problem.
