### ISSUE TITLE
Nightly travis tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#697]
They appear to be [timing out on some tests](https://travis-ci.org/choderalab/yank/jobs/241806897#L1320).

Any idea how we can fix this? Should we exclude additional slow tests?

**Comment by andrrizzi** [comment]
I think tests are taking longer because now we [compute and store the energy](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L1593-L1597) at iteration 0. I can probably bring that calculation inside the while loop [here](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L1609).

The easiest way to make that test pass is probably to test a solvation free energy instead of a receptor-ligand system (it's just testing that the command is running anyway).
