### ISSUE TITLE
Implement restraints referenced to center of geometries of atom selections

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#736]
This is just a placeholder to remind us that we will need to implement variants of the `Harmonic` and `FlatBottom` restraints that use the centers of geometry of DSL-specified atom selections in order to carry out host-guest (and like T4 lysozyme) binding free energies for the paper.

We can use [`CustomCentroidBondForce`](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomCentroidBondForce.html#simtk.openmm.openmm.CustomCentroidBondForce) for this purpose. For example, `Harmonic` would use something like this
```
# Harmonic restraint between two groups of atoms
num_groups = 2
force = openmm.CustomCentroidBondForce(num_groups, "(K/2)*distance(g1,g2)^2")
force.addGlobalParameter("K", K)
force.addGroup(particles1); # create group 0
force.addGroup(particles2); # create group 1
force.addBond([0,1], []); # add bond between groups 0 and 1
system.addForce(force)
```

**Comment by andrrizzi** [comment]
Thanks for the directions @jchodera ! I'll work on this today.

Is the DSL selection necessary for 1.0? Can we add that afterward? It will take a week to add that feature to YAML, and for the paper, we could just use atom indices for now like the other restraints since the receptor doesn't change. In this case, we would automatically select the ligand atom.

**Comment by andrrizzi** [comment]
I'd also prefer to implement the general DSL region feature in YAML after we have implemented multiple alchemical regions in `openmmtools.alchemy` so that we can be sure they'll be integrated properly.

**Comment by andrrizzi** [comment]
Ah sorry, unless you meant that the restraint object can take a DSL string during initialization. I think can add this easily.

**Question**: am I correct in thinking that the standard state correction in this case should be computed very similarly to the standard `Harmonic` restraint (i.e. integrate shell volume and compute log ratio with standard volume)?

**Comment by jchodera** [comment]
> Ah sorry, unless you meant that the restraint object can take a DSL string during initialization. I think can add this easily.

Yes, this is what I meant! Since the ligand atom indices will be different for each ligand, I think it would be a nightmare without the ability to at least specify the ligand residue name.

> Question: am I correct in thinking that the standard state correction in this case should be computed very similarly to the standard Harmonic restraint (i.e. integrate shell volume and compute log ratio with standard volume)?

Yes, as I understand it, the corrections would be identical to the case where only a single atom is chosen for receptor and ligand.

**Comment by andrrizzi** [comment]
> the corrections would be identical

Do we actually need separate classes then? The current `Harmonic` and `FlatBottom` would be just a particular case of the new restraints with only 1 atom per group. Or is there another difference?

I don't think that the loss of performance caused by `CustomCentroidBondForce` would be perceivable with only 1 bond, but we can still implement `_create_force()` to use a normal `CustomBondForce` in case the groups are composed of only one atom if that turns out to be the case.

**Comment by jchodera** [comment]
> Do we actually need separate classes then? The current Harmonic and FlatBottom would be just a particular case of the new restraints with only 1 atom per group. Or is there another difference?

That works for me!

**Comment by davidlmobley** [comment]
I'm just commenting so I can follow this discussion. Thanks for working on this.
