### ISSUE TITLE
Document how to select flat bottom restraints size

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#765]
Is there a mechanism to control the size of the flat bottom of the flat bottom restraining potential? We would very much like to be able to do this to assist with our benchmarking to compare the relative efficiency of flat bottom restraints, no restraints, and Boresch-style harmonic restraints. We've not been able to find anything in the docs on this.

It would also be useful to know how the size of the flat bottom potential is determined. 

cc @elkhoury

**Comment by jchodera** [comment]
I think you should be able to specify the `well_radius:` parameter in the restraints block, as in
```YAML
  restraint:
    type: FlatBottom
    well_radius: 1.0 * nanometers
```
@Lnaden : Might want to document this!

**Comment by davidlmobley** [comment]
Thanks. Changing the title of the issue to reflect it's documentation which needs updating. :)

**Comment by Lnaden** [comment]
Right now, the [Restraints section of the YAML docs](http://getyank.org/0.17.0/yamlpages/experiments.html?highlight=restraint#experiments-syntax) says the following:

>Every restraint has his own set of optional parameters that are passed directly to the Python constructor of the restraint. See the API documentation in `yank.restraints` for the available parameters.

Which was meant to be a catchall for restraint keywords since each type of restraint has different arguments. That is not sufficiently clear it seems, so there are a few ways I can approach this; which sounds better:

1. Link to each restraint type in the API docs 
    * My choice, less space and clutter, avoids repetition
2. Re-post the API options for each restraint entirely on the page 
    * Complete, but cluttered
3. Manually document each restraint type and option. 
    * Can be formatted to be prettiest, highest maintenance load, highest chance of error

**Comment by jchodera** [comment]
For now, let's try option 1 and do something else if this is still unclear.

**Comment by davidlmobley** [comment]
Yes, I agree with option 1 being the best option. Having to know where to look in the docs to find a particular topic (API vs YAML) is not the easiest route to get started.

(Probably we are currently a good test case for whether you're hitting your intended audience; we have no idea how to use Yank mostly, but have some expertise in free energy calculations as a group though the people working on these calculations are new to free energy but (at least in some cases) experienced with other MD packages. That's part of why I'm having them post issues on docs, snags, etc. -- I figure we're basically your "target audience" at this point.)
