### ISSUE TITLE
Schema Error Trapping in YAML validation sucks

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#795]
Outputs from Schema sucks sometimes, the best we can tell is "something" went wrong, and all our custom thrown errors are getting consumed.

I have been tracing what is happening in the `Schema` backtrace and think I know why this is happening. The `Or` operator for Schema is eating our error traces. It consumes all but the final error instead of collecting specifically as [this code here](https://github.com/keleshev/schema/blob/56262d770a39f71bbebb7ae2acc153027c1065c8/schema.py?utf8=%E2%9C%93#L116-L117). If we split up our systems schema from `Schema(Or(...` into a series of `Schema(...)` where we manually handle the top level `Or()` comparator in our own code, we could better (and actually) intercept error messages with proper handling.

This also may not be a full fix, but would be an improvement.

I don't think this would be *hard* as much as it would be *time consuming* to fix (maybe a day), thoughts?

**Comment by davidlmobley** [comment]
Speaking as a Yank novice (but someone who has done lots of free energy calculations) it seems to me that providing better error messages is going to be crucial. Right now I worry that the only way people are going to be able to use Yank is that if they use it for something that is almost exactly like what you guys have done already/provided in examples and tutorials. I've only deviated from that **very slghtly** -- trying to take something which you had gotten working earlier in the year and adjust it just slightly -- and it's been very painful because the error messages (and logging, I suppose) have been so unhelpful. 

Better logging could help too, I think. In my case, even when I'm able to figure out what's going on -- e.g., it's trying to set up TIP4PEw even though I'm going to be conducting an implicit solvent simulation -- I'm left with the question, "wait, why is it trying to set that up?" which could be answered by logging information which said what setups it is doing and why as it uses the YAML. Now I know the answer -- it's because it does setups specified in the YAML even if they aren't going to be used -- but this was not clear. 

Anyway, just my two cents.

**Comment by jchodera** [comment]
I definitely agree, @davidlmobley. We discussed ways to handle this just now, and will focus on this aspect of usability over the next couple of weeks.
