### ISSUE TITLE
Default choice for the FlatBottom restraint's parameters results in shell volume larger than the box.

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#806]
Opening this issue to keep records.

So far we've been using a spring constant of 0.6kcal/mol/A^2 and a well radius determined by:
```python
sigma = 1.4826 * median_distance
well_radius = 2*sigma + 5.0 * unit.angstroms
```
where `median_distance` is the median distance between the restraint centroid and the receptor atoms. For host-guest systems, the median distance ends up being very close to the maximum distance. As a consequence, the well radius ends up being about 3 times the maximum distance (+ 5 angstroms), and the restraint shell volume sometimes exceeds the solvation box.

I'll add a check that raises an exception if this is the case, I'll tighten the default spring constant to 10kT/A^2, and I'll compute the well radius as
```python
well_radius = max_dist_receptor + max_length_ligand/2 + 5*unit.angstrom
```
where `max_dist_receptor` is the maximum distance between restraint centroid and receptor atoms, and `max_length_ligand` is the maximum distance between any pair of ligand atoms.

**Comment by jchodera** [comment]
@davidlmobley may be interested in this fix.

**Comment by davidlmobley** [comment]
cc @elkhoury

For the record can you clarify what problem currently results when the restraint shell volume exceeds the box? I assume that there's an entropic contribution which is not included in computing the relevant restraint correction?

**Comment by jchodera** [comment]
> For the record can you clarify what problem currently results when the restraint shell volume exceeds the box? I assume that there's an entropic contribution which is not included in computing the relevant restraint correction?

There are several problems:
1. The standard state correction will be inaccurate because it does not restrict the integral to the box volume
2. The restraint force is periodic, but will not be continuous everywhere, which is not generally a problem except this situation likely indicates this discontinuity is thermally accessible in simulation timescales
3. The restraint force may not keep the ligand close enough to the receptor to speed up convergence
