### ISSUE TITLE
unknown parameter number_of_iterations

### ISSUE THREAD

**Issue by dprada** [choderalab/yank#956]
Yank 0.21 (omnia channel -conda-) does not recognize the yaml option 'number_of_iterations'.

In Yank 0.20 this option was introduced in the dictionary template_options with the line 1207 of experiment.py:

```
        template_options.update(utils.get_keyword_args(repex.ReplicaExchange.__init__))
```

This fact makes the examples not functional.
I hope this helps to keep the stable version usable for the new users experimenting with yank.

Thanks a lot.

**Comment by Lnaden** [comment]
YANK 0.21.0 was a significant refactor of YANK's code base which included a generalization of the sampling scheme introducing a generic, fixed state `MultiStateSampler`; the Hamiltonian Replica Exchange sampler `ReplicaExchangeSampler`; and the single-replica state jumping self-adjusted mixture sampling `SAMSSampler`. As part of this generalization, the YAML files were changed to include two additional blocks `samplers` and `mcmc` which control sampler-specific and Markov Chain Monte Carlo-specific options, respectively. 

We decided to move a couple options such as `number_of_iterations` from the general `options` block to their respective `samplers` and `mcmc` blocks to avoid ambiguity since multiple samplers can now be provided. The `samplers` and `mcmc` blocks are fully optional and a default set of options will be chosen if you do not specify them, and to facilitate backwards-like behavior, we renamed the option in the primary `options` block to `default_number_of_iterations`. If you want to restore the previous behavior, simply exchange `number_of_iterations` with `default_number_of_iterations` in your `options` block, although we encourage experimentation with the new blocks as well.

See http://getyank.org/latest/yamlpages/samplers.html for more information about the new block and look over the [changelog](http://getyank.org/latest/whatsnew.html#sams-and-general-multistate-samplers) to see how YANK's structure has changed in 0.21.0

**Comment by dprada** [comment]
Thanks for your kind reply!
I am going to have a look.

**Comment by jchodera** [comment]
Our apologies for the ever-changing API! We hope this is very close to a final stable release! Things should be much more stable once the initial preprint is posted!

**Comment by dprada** [comment]
No need to apologize. 
You are doing a great effort and a fantastic job. I had to look more in detail before opening the issue.
Thanks.
