### ISSUE TITLE
Speed up `yank analyze` to usable speeds by eliminating time-consuming unnecessary steps

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#980]
Currently, `yank analyze` run on SAMS trajectories takes an horrifically long time.

We need to prune out inessential computations and do what we can to accelerate this.

Some ideas:
* Eliminate the calls to [`show_mixing_statistics`](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L110) in calls to [`analyze_phase()`](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L108) since this data is only printed and not captured in any way. This call is slow.
* The call to [`pymbar.timeseries.detectEquilibration()`](https://github.com/choderalab/yank/blob/master/Yank/multistate/utils.py#L111) currently uses [`nskip=1`](https://github.com/choderalab/pymbar/blob/master/pymbar/timeseries.py#L739-L747) by default. This should be automatically selected so that ~40-100 time origins are considered for equilibration, since there is no point in considering every snapshot in a 30,000-snapshot energy trace a as a potential time origin.

**Comment by Lnaden** [comment]
> Eliminate the calls to show_mixing_statistics in calls to analyze_phase() since this data is only printed and not captured in any way. This call is slow.

`show_mixing_statistics` function calls `generate_mixing_statistics` which does store the mixing statistics, but nothing else uses them. So I'll silence them by default.

> automatically selected so that ~40-100 time origins are considered for equilibration

Do you mean to consider only 40-100 total samples when figuring out the equilibration point? That seems like its a bit low. Would you accept 1000 max? That would still speed things up while still keeping a large number of samples to figure out.

**Comment by jchodera** [comment]
The important thing is to only consider a limited number of time origins. If you can do 1000 and still have it be fast, by all means go for it!

Alternatively, you can expose an option and set this to something like 100 by default. We can tweak the default later.

**Comment by Lnaden** [comment]
My idea is to allow a either `nskip` or `noutput` or something where you set either how many to skip or how many maximum data points you want, defaulting to 1000 output.

**Comment by jchodera** [comment]
I would very much prefer `nequilorigins`: Set the number of potential time origins to examine for equilibration end. This would ensure the automated equilibration detection takes nearly constant time regardless of simulation length.

**Comment by Lnaden** [comment]
> nequilorigins: Set the number of potential time origins to examine for equilibration end.

That sounds just like the `noutput` (its a bad name) I had from above: consider Y number of iterations for detecting equilibration, evenly spaced out over the timeseries. e.g. if Y=1000 and there are 30000 samples, it will only consider every 30 iterations or so. 

> This would ensure the automated equilibration detection takes nearly constant time regardless of simulation length.

This is a very different problem since the `detectEquilibration` function actually cycles from `t:T` for every point in some series `T` indexed by `t`. I think I know what you mean here, but I will write it out explicitly to avoid confusion:

Option 1 (my original idea):
Run the equilibration data per sample jumping every X iterations such that the final output is roughly equal in shape no mater the simulation length, but allow the `detectEquilbration` function for computing the equilibration data to operate on the whole `t:T` range where `t = [0, X, 2X, 3X.... T]`

Option 2 (your suggestion):
Do everything from option 1 except also uniformly subsample the timeseries passed into `detectEquilbration` such that `detectEquilibration` only considers the points along X as well, operating on `t:T:X`.

**Comment by Lnaden** [comment]
For documentation:

We determined what we want is a problem which scales as O(N) with N number of samples, not O(C) where C is some constant independent of N
